### ISSUE TITLE
 readme.md incomplete

### ISSUE THREAD

**Issue by VNRARA** [blunden/SPayToGPay#1]
Pls update readme.md to include the xda explaination. I missed the reboot part untill I started looking on XDA for other comments on this.

**Comment by blunden** [comment]
Good suggestion. I should definitely do that. :) 

The reason it isn't already in there is because I didn't know it was needed at the time of writing it, simply because I can't test this app on my own watch (signature mismatch due to Samsung Pay being preinstalled).

**Comment by blunden** [comment]
I updated both the readme and the two release descriptions with information about the need to reboot.
