### ISSUE TITLE
Galaxy watch 6

### ISSUE THREAD

**Issue by hamid-vasefi** [blunden/SPayToGPay#4]
_Unfortunately, the current version (v1.2) can not be installed on GW6, probably due to a different os version (WearOS 4) and if that is the case, the app will stop working on previous models after os update.
I was wondering if the app can be updated to work with the newer version._

Edit: My mistake. Samsung Wallet is pre-installed in my region, but it is not accessible by the watch (app list, app drawer, or back button long press) so GW4Remap for example can not be used.

**Comment by blunden** [comment]
Does your watch have Samsung Pay preinstalled? If so, that's why.

If not, let me know the exact error you get when trying to install it.

**Comment by hamid-vasefi** [comment]
> Does your watch have Samsung Pay preinstalled? If so, that's why.
> 
> If not, let me know the exact error you get when trying to install it.

Thank you for your kind follow up

_My watch does not have Samsung pay installed_ (Edit: it does!!!)

Please find attached screenshots of two different apps, that failed to install the app:
![Screenshot_20230823_195418_Wear Installer 2](https://github.com/blunden/SPayToGPay/assets/142950810/e9453257-d8d4-436e-9825-101cb8ca6821)
![Screenshot_20230823_195859_Bugjaeger](https://github.com/blunden/SPayToGPay/assets/142950810/7eed51bd-b6c1-4d75-9aa9-06ffd80bbec3)

**Comment by blunden** [comment]
Hmm, weird. Any chance you could try directly with ADB in order to get the detailed error message?

It might be that the app simply needs to target a later API level. I can try that later.

**Comment by hamid-vasefi** [comment]
To be honest, I'm very new to watch world, and I'm not very familiar with adb

if you can kindly let me know how I'll try.

**Comment by blunden** [comment]
Give this APK a try:

https://www.mediafire.com/file/7avfmeah72dp0ja/SPayToGPay-v1.3-test.apk/file

If it doesn't work, check this guide for enabling ADB debugging on your watch and connecting to it from your PC:

https://droidwin.com/how-to-set-up-and-enable-adb-debugging-in-galaxy-watch-4/

**Comment by hamid-vasefi** [comment]
Thank you very much for the effort, but unfortunately it did not work.
I'll try to use adb with my PC later today and I'll let you know if it works.
Just to make sure, after connecting to pc with adb, should I use adb install app.apk? Just like using adb to install apps on the phone?

**Comment by blunden** [comment]
Ok. Thanks for testing it.

Once you have ADB set up, the command to install an APK is:

`adb install filename.apk`

**Comment by hamid-vasefi** [comment]
Hi again!
I tried installing using ADB on my PC, but it failed again.
here is the error message:
adb: failed to install SPayToGPay-v1.3-test.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.samsung.android.samsungpay.gear signatures do not match newer version; ignoring!]

I was shocked as I knew Samsung Pay is not available in my country.
So I used Bugjaeger tool and found out there **IS** a Samsung wallet installed on my watch. But it is not accessible. I'm really sorry. It is not available neither in the app drawer nor in the app list. And I can not open it with the tool either. I used GW4Remap and that also did not work.
Is it safe to remove the pre-installed app and install your file?
If yes, should I go with version 1.2 or 1.3?

**Comment by blunden** [comment]
Ok, so it had the app preinstalled after all. It doesn't surprise me as only a few regions shipped without it when it comes to the Watch 4 and 5 series.

No, it's a system app (the system partition is read-only) so even though you can "uninstall" it,  that simply disables it. You can never install another app with the same package name but a different signature. Instead, you will have to use [SPayRemap](https://www.reddit.com/r/GalaxyWatch/comments/v0c44x/spayremap_an_app_for_the_galaxy_watch_4_to/) or [GW4Remap](https://github.com/BigBoot/GW4Remap) instead.

**Comment by hamid-vasefi** [comment]
> Ok, so it had the app preinstalled after all. It doesn't surprise me as only a few regions shipped without it when it comes to the Watch 4 and 5 series.
> 
> No, it's a system app (the system partition is read-only) so even though you can "uninstall" it, that simply disables it. You can never install another app with the same package name but a different signature. Instead, you will have to use [SPayRemap](https://www.reddit.com/r/GalaxyWatch/comments/v0c44x/spayremap_an_app_for_the_galaxy_watch_4_to/) or [GW4Remap](https://github.com/BigBoot/GW4Remap) instead.


I'm really sorry you had to go through all the hassle just because of my lack of knowledge. I had tried GW4Remap but it did not work as Samsung pay will not open. let me try the other one and I'll let you know if it works.
Thanks again for all your help.

Edit: As I imagined, it did not work either as Samsung pay will not load, so the app can not override it

Edit: I am LOST!
I uninstalled the app using adb shell, now it is not in the packages list, but it fails to install again and says app is available. i would really appreciate if you could help me on that.

**Comment by blunden** [comment]
No worries. 🙂

I see. In that case, I think there is a version of GW4Remap that works by reading the system log to look for attempts to launch Samsung Pay, instead of the original method of using the Accessibility API to get callbacks when Samsung Pay is launched. That one might work even in cases like yours.

**Comment by hamid-vasefi** [comment]
I tried that with no luck :(
I really wanted to make it work, but none of the apps seem to work in my case :((

Since SPay is pre-installed, your app will not work.
Since it will not launch, SPayRemap and GW4Remap v1 will not work.
Since I can not assign the Power button long press to Bixby after disabling it, GW4Remap v2 alpha will not work

Anything else I may be missing?

**Comment by blunden** [comment]
Then don't disable the Bixby app. Just don't use it

**Comment by hamid-vasefi** [comment]
I tried, did not work. long pressing the power button would open Bixby, not the app I assigned
Long pressing the back button does not do anything. :(

**Comment by hamid-vasefi** [comment]
Hi again,

Sorry to bother you with this again.
I know it does not have anything to do with your app, but unfortunately it looks like gw4repam app in abandoned by the creator and I can not get any help there.
I was wondering maybe you can help me.

I am looking forward to your kind reply.

**Comment by blunden** [comment]
You could try to enable the Samsung Pay app using ADB:

1. adb shell 

2. pm enable com.samsung.android.samsungpay.gear

**Comment by hamid-vasefi** [comment]
Thanks.

It says package enabled, but it won't run.
Can you send me your Samsung pay apk? maybe I can replace it with mine and then maybe it would work?!

**Comment by blunden** [comment]
GW4 Remap still works fine for me on Wear OS 4.0. Are you sure you actually enabled the accessibility service in settings?
