### ISSUE TITLE
SPayToGpay stopped working after WearOS 4 (OneUI 5) update.

### ISSUE THREAD

**Issue by 4k3or3et** [blunden/SPayToGPay#5]
Hi there,

My Galaxy Watch 4 Classic just got update to Wear OS 5. Unfortunatelly SPayToGpay stopped working after update. I have tried to install app again but logner press of a button does not invoke Google Wallet. Is there any chance developer would spend some time trying to fix the issue on Wear OS 5? I am happy to test just in case.

Thanks anyway :-)

**Comment by blunden** [comment]
Yeah, I've heard that but I am unable to debug the app myself since I'm in a region where my app can't be installed.

I need a logcat log from slightly before, during and after the button shortcut is attempted to have any chance of tracking down the issue.

Is that something you are able to get me?

**Comment by 4k3or3et** [comment]
I can definitely try. Can you let me know how to perform logcat?

**Comment by blunden** [comment]
This guide shows you how to set up ADB:

https://droidwin.com/how-to-set-up-and-enable-adb-debugging-in-galaxy-watch-4/

Once that's done and you've connected to the watch as described there, try running "adb logcat".

If you see a bunch of text filling up your terminal, press CTRL+C to cancel it. Then:

1. Run "adb logcat > /sdcard/log.txt" to write it to a file.

2. Try triggering the Samsung Pay button shortcut a few times.

3. Press CTRL+C

4. Run "adb pull /sdcard/log.txt ." (note the period at the end) to copy the log file from the watch to the directory your terminal is currently pointing at.

5. Send me that file to support [at] blunden.se.

**Comment by 4k3or3et** [comment]
I think i have it :-)

I have sent you the logcat log file on the mail which you specified above.

I have invoked Samsung Pay button (long press) 5 times during capturing the log with couple of second pause between each press and hold. If there is anything wrong with that log or you need anything else please let me know, i am happy to cooperate with you to get that issue possibly fixed.

Thanks a million for taking time to look into this matter. I truly appreciate that especially that for you that app is of no use.

**Comment by blunden** [comment]
Thanks! I have received it.

It might be a fiew days until I have a chance to look at it.

**Comment by mk89pwnz** [comment]
Looking forward for this to work again :)

**Comment by blunden** [comment]
I make no promises. 🙂

**Comment by VNRARA** [comment]
@blunden you need the new name of the Samsung pay app right?

**Comment by blunden** [comment]
I would expect the package name to remain the same. The activity name might have changed though, I suppose.

I'll pull the apk from my watch once the update has finished installing.

**Comment by VNRARA** [comment]
This it? 

09-12 21:56:33.076   545   728 D InputDispatcher: set entryflags to AKEY_EVENT_FLAG_LONG_PRESS
09-12 21:56:33.176   545   545 D WindowManager: stemPrimaryLongPress behavior=101
09-12 21:56:33.177   545   545 D PhoneWindowManagerExt: spay state = 0
09-12 21:56:33.177   545   545 D PhoneWindowManagerExt: broadcast samsung pay intent
09-12 21:56:33.177   545   545 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1194 com.android.server.policy.PhoneWindowManagerExt.sendBroadcastSamsungPay:1439 com.android.server.policy.PhoneWindowManagerExt.stemPrimaryLongPress:1418 com.android.server.policy.PhoneWindowManager.stemPrimaryLongPress:1743 com.android.server.policy.PhoneWindowManager.-$$Nest$mstemPrimaryLongPress:0 
09-12 21:56:33.197   303   305 I tzdaemon: [il] name of requested image: 00000000-0000-0000-0000-0053545354ab; cmd type 1
09-12 21:56:33.198   303   305 D tzdaemon: [il] resolved full_name /vendor/tee/00000000-0000-0000-0000-0053545354ab
09-12 21:56:33.198   303   305 I tzdaemon: [il] Found file:/vendor/tee/00000000-0000-0000-0000-0053545354ab size:56267
09-12 21:56:33.199   303   305 I tzdaemon: [il] Created container shared memory 0xf04f7000 size 56267
09-12 21:56:33.199   303   305 D tzdaemon: [il] reply.image.buf_desc.size 56267; reply.image.buf_desc.id 4
09-12 21:56:33.199   303   305 D tzdaemon: [il] image_loader_event_loop(): going to send reply (76 bytes) to sfd:9

**Comment by blunden** [comment]
I made some blind changes here based on the manifest of the new Samsung Pay app:

https://www.mediafire.com/file/vdy4u4uijmlvekv/SPayToGPay-v1.3-wearos-4.0-test.apk/file

It includes a number of new activity-aliases as well as a broadcast receiver that looked potentially interesting.

This is completely untested of course. Make sure to reboot the watch after installing.

**Comment by VNRARA** [comment]
No dice. Didn't work :(

**Comment by blunden** [comment]
Hmm, ok.

This line in the log seems potentially interesting:

> W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1194 com.android.server.policy.PhoneWindowManagerExt.sendBroadcastSamsungPay:1439 com.android.server.policy.PhoneWindowManagerExt.stemPrimaryLongPress:1418 com.android.server.policy.PhoneWindowManager.stemPrimaryLongPress:1743 com.android.server.policy.PhoneWindowManager.-$$Nest$mstemPrimaryLongPress:0

That's why I implemented the receiver that I thought it refers to (based solely on the name). I haven't bothered to decompile PhoneWindowManagerExt to see what the sendBroadcastSamsungPay method actually does yet. I guess I'll need to do that at some point.

**Comment by VNRARA** [comment]
If I may be so bold: What did you change? I have the project open in Android Studio, but I'm a noob xD

**Comment by blunden** [comment]
This is the manifest from the latest test APK:

https://gist.github.com/blunden/4404f2a6593b582d16b6dcb908f8b7be

I also implemented a simple `WalletLaunchReceiver`.

**Comment by blunden** [comment]
It seems they didn't bother to obfuscate the `PhoneWindowManagerExt` class in /system/framework/services.jar:

https://pastebin.com/00L6cnJu

@VNRARA Can you check the logcat log for "SPayToGPayWalletLaunchReceiver" when performing the shortcut? I'm curious if it gets called at all.

**Comment by VNRARA** [comment]
With the v1.3 app correct? Also I noticed that : android.intent.category.INFO => android.intent.category.LAUNCHER

**Comment by blunden** [comment]
Yes, with the v1.3 test app above. :)

**Comment by VNRARA** [comment]
huh... 

09-13 01:18:40.035 15189 15189 E SPayToGPayWalletLaunchReceiver: Failed to start Google Pay activity
09-13 01:18:40.035 15189 15189 W System.err: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

Running the v1.2 activity command via adb did work tho..

**Comment by blunden** [comment]
@VNRARA Thanks! Try the APK below and provide me the log output from when it fails. The same search you used last time should work.

https://www.mediafire.com/file/ephii59atj6zxhm/SPayToGPay-v1.3-wearos-4.0-test-2.apk/file

I'm a little concerned that Android will prevent it from launching the Google Pay app due to the limitations imposed in Android 10. Samsung's app has a special permission to launch apps from the background that can't be granted to my app. I suppose it might be possible to abuse the SYSTEM_ALERT_WINDOW permission, but I don't know if there is a UI for granting that on Wear OS, or if it can be granted with "pm grant".

https://developer.android.com/guide/components/activities/background-starts

**Comment by VNRARA** [comment]
I'm not sure. Am I supposed to look for SPayToGPayWalletLaunchReceiver ? Cause that isn't showing.

**Comment by blunden** [comment]
Yes, I would've expected it to print a line about receiving the broadcast when you press the button shortcut. It doesn't anymore?

Did you reboot the watch (unless that wasn't needed last time)?

**Comment by VNRARA** [comment]
I rebooted twice for good measure after installing the SPayToGPay-v1.3-wearos-4.0-test-2.apk via adblink2 

[logv132_2.txt](https://github.com/blunden/SPayToGPay/files/12591756/logv132_2.txt)

We can do some more testing tomorrow. GTG sleep. EU/AMS timezone here


What if you make the app pretty and abuse this: 

"The app has an activity in the back stack of an existing task on the [Recents screen](https://developer.android.com/guide/components/activities/recents)."

**Comment by blunden** [comment]
Perhaps you could uninstall and then reinstall the SPayToGPay-v1.3-wearos-4.0-test-2.apk again? Maybe the system just stopped sending the broadcasts to it for some reason.

Clearly, your last log snippet showed that it was being called (but threw an exception later when trying to launch the Google Pay app without FLAG_ACTIVITY_NEW_TASK). All I changed was to add that flag to the intent before calling context.startActivity(activityIntent). Even if that call to startActivity failed, I would've expected to see some other exception and a log line saying "SPayToGPayWalletLaunchReceiver: onReceive(): com.samsung.android.wearable.sysui.action.CHECK_AND_LAUNCH_WALLET" before that.

**Comment by blunden** [comment]
You could also try what I mentioned above with this new APK instead (after you grant it the permission needed):

https://www.mediafire.com/file/58tkfl0bv7sz5gt/SPayToGPay-v1.3-wearos-4.0-test-3.apk/file

To grant the permission, run the following command:

`adb shell pm grant com.samsung.android.samsungpay.gear android.permission.SYSTEM_ALERT_WINDOW`

**Comment by tomskra** [comment]
I just  tried SPayToGPay-v1.3-wearos-4.0-test-3.apk with granted SYSTEM_ALERT_WINDOW permission command and it's working !! 👍

**Comment by blunden** [comment]
Awesome! I'll push the code and upload an official APK. Apart from removing an extra line of debug logging, it should be functionally the same though.

Thank you all for providing me the necessary logs and testing. :)

**Comment by blunden** [comment]
Fixed in version 1.3 available under Releases.

**Comment by mk89pwnz** [comment]
Thanks a lot... also I needed some googling to figure it out, you need latest adb on your pc to first pair the watch then connect to it, it's not that simple like before and to use PowerShell instead of cmd, but now everything is working :)

**Comment by blunden** [comment]
@mk89pwnz Yes, that pairing process was new to me too. 😄 Surprisingly, it wasn't as well documented as I expected it to be.

**Comment by VNRARA** [comment]
@blunden srry for being late to the party today. Will install later too. 

FYI: The mediafire link is dead.

**Comment by VNRARA** [comment]
NB: may not work immediately after boot.

@blunden it's a bit groggy after boot: it doesn't come as snappy as it used to.

**Comment by blunden** [comment]
But it doesn't require you to grant the permission again?

I don't think there is much I can do about that.

**Comment by VNRARA** [comment]
No worries. It was more of a nota bene for other users.

**Comment by blunden** [comment]
@VNRARA But the performance goes back to normal a while after boot?

**Comment by VNRARA** [comment]
Yeah, it seems back to normal after.

**Comment by 4k3or3et** [comment]
@blunden, Thanks a million for sorting this out. Works fine :-)

I have noticed massive improvement in comparison to version 1.2. On 1.2 you could open Google Wallet using Samsung Pay button only when you were on watch face screen. If you had and app opened or were in setting you had to go to face watch screen and then you could open Google Wallet using Samsung Pay button. On version 1.3 no matter what you have on the screen at the moment, pressing Samsung Pay button always opens Google wallet. Not sure if that is thanks to adb permission command which you have now execute after installation or @blunden changed the code but this is actually great feature to have! Thanks again!

**Comment by blunden** [comment]
@4k3or3et My understanding is that it is a result of changes made by Samsung. I won't claim any credit for it, but I'm happy that people see an improvement in functionality. 😀

To me, it's mostly about solving problems and enjoying building PoCs that end up working for people. In this case, the target audience is definitely the smallest of any of my modded apps etc. but it's still fulfilling. 🙂
